apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ps-app-ui3_mapping
      host: ps.jenkins.c.eu-de-1.cloud.sap
      prefix: /ps/app/ui/
      rewrite: /ps/app/ui/
      service: {{ template "name" . }}.{{ .Values.ns }}:{{ .Values.servicePort }}
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ps-app-ui4_mapping
      host:  ps.jenkins.c.eu-de-1.cloud.sap
      prefix: /
      service: {{ template "name" . }}.{{ .Values.ns }}:{{ .Values.servicePort }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
  - name: http1
    port: {{ .Values.servicePort1 }}
    targetPort: {{ .Values.containerPort1 }}
  - name: http2
    port: 83
    targetPort: 8766
  - name: http3
    port: 82
    targetPort: 8765
  selector:
    app: {{ template "fullname" . }}
